### ISSUE TITLE
Update Download dialog box with descriptions in David Stroud's widget

### ISSUE THREAD

**Issue by LuAnn** [nemac/data_snapshots#59]
(I'm not sure if this was on a list from David Stroud or not, so I'm posting it here)

We recommended some additional description beyond the pixel widths.  Click Download at http://www.cpcpara.ncep.noaa.gov/datSnapWebBuild/datSnap_Dev1.php to see them.
Note that the two columns aren't vertically aligned in David's widget, but I hope they will be in the real deal. :)

**Comment by frimmel** [comment]
Fixed on the server side
