### ISSUE TITLE
Add a URL field that will link to the "NOAA Data Product" link text

### ISSUE THREAD

**Issue by LuAnn** [nemac/data_snapshots#72]
Adding a URL link to this text field will make this the primary link to send folks to the original data product from which we developed the snapshot.

Also, as "NOAA Data Product" doesn't cover all of our datasets anymore, please change the link text label to "Source Data Product"

**Comment by frimmel** [comment]
This has been implemented and I will be pushing up a patch to close this issue shortly, but since the field type has been changed to a link the content in it will need to be re-entered.
