### ISSUE TITLE
A suggestion about links

### ISSUE THREAD

**Issue by LuAnn** [nemac/data_snapshots#76]
Is it possible to have links on the Dataset Details pages default to opening in a new window/tab? 

In my view, if someone is reading about a particular set of snapshots, they might open the linked pages to learn more, but when they want to go back, they have been thrown out of the interface and have to zero in on the map they want again.

I recognize that letting the user decide for themselves if they want to open a new tab is also just fine.
Just a suggestion.

**Comment by frimmel** [comment]
Hi LuAnn,

I have implemented this and will be pushing up a fix shortly, but I wanted to let you know that right now the Data Snapshots widget will update your browsers history as you interact with it. So a user navigates away from Data Snapshots they will be able to hit the back button to return to the map they were looking at.
