### ISSUE TITLE
Update an internal link

### ISSUE THREAD

**Issue by LuAnn** [nemac/data_snapshots#79]
In the Maps tab, the "About this snapshot" blurb at the bottom has a » character that is link to activate the Descriptions tab. 

I'm feeling like adding the word "more" or even "read more" ahead of the character and linking the text to the appropriate Dataset Details page instead of just the Description tab would be more satisfying.
For example, it would look like this for total precip:
<b>About This Snapshot:</b>
Colors show monthly precipitation totals for each 
of the 344 climate divisions in the contiguous 
United States.   <b>read more »</b>

And the <b>read more »</b> would link here:  http://dss-dev.nemac.org/data-snapshot/data-source-total-monthly-precipitation

This way, both <b>read more »</b> links would go to the same place.

**Comment by LuAnn** [comment]
I see the » character now links to the Dataset Details page (after a brief
look at the Descriptions tab), but I also hoped you'd add the words "read
more" to that field. I don't think many folks will find the single
character link.

On Tue, Feb 24, 2015 at 8:51 AM, John Frimmel <notifications@github.com>
wrote:

> Closed #79 <https://github.com/nemac/data_snapshots/issues/79> via 2391c4c
> <https://github.com/nemac/data_snapshots/commit/2391c4cc04362ec3fefe73f3bcd8d5ee07c3de9c>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nemac/data_snapshots/issues/79#event-241003214>.
>



-- 
LuAnn Dahlman
Communication Specialist
NOAA Climate Program Office
2020 LLC
*an Acentia Company*
Phone:  480-734-3124

**Comment by frimmel** [comment]
Whoops, I misinterpreted that part of your issue. I thought you were referring to the link on the other tab in your description. This issue should be properly fixed now!

**Comment by LuAnn** [comment]
Just what I was hoping for!!

I'm really appreciative of your quick responses and complete solutions to
these last few issues.

All smiles,
LuAnn

On Tue, Feb 24, 2015 at 9:28 AM, John Frimmel <notifications@github.com>
wrote:

> Whoops, I misinterpreted that part of your issue. I thought you were
> referring to the link on the other tab in your description. This issue
> should be properly fixed now!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nemac/data_snapshots/issues/79#issuecomment-75789922>.
>



-- 
LuAnn Dahlman
Communication Specialist
NOAA Climate Program Office
2020 LLC
*an Acentia Company*
Phone:  480-734-3124
