### ISSUE TITLE
A simple design tweak (please)

### ISSUE THREAD

**Issue by LuAnn** [nemac/data_snapshots#80]
In the Description pane of the main interface, I'd prefer to see the secondary question placed directly below the answer to the Framing question, rather than maintaining a big blank between them as Dave Stroud suggested. 
For example, the amount of space currently between the first answer and the second question for <b>Drought Outlook</b> looks good. An example of what I don't like is on Total Monthly Precipitation. The big blank on that one feels like a mistake to me.

**Comment by frimmel** [comment]
Hi LuAnn,

I have tightened up the spacing on these elements. Should I give them slightly more breathing room or should we use this new display?

Thanks!

John

**Comment by LuAnn** [comment]
The new spacing looks good to me. The different font styles helps keep them
separate.

Thanks for checking smiles,
LuAnn

On Tue, Feb 24, 2015 at 7:53 AM, John Frimmel <notifications@github.com>
wrote:

> Hi LuAnn,
>
> I have tightened up the spacing on these elements. Should I give them
> slightly more breathing room or should we use this new display?
>
> Thanks!
>
> John
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nemac/data_snapshots/issues/80#issuecomment-75770368>.
>



-- 
LuAnn Dahlman
Communication Specialist
NOAA Climate Program Office
2020 LLC
*an Acentia Company*
Phone:  480-734-3124
