### ISSUE TITLE
url alias for default entry point

### ISSUE THREAD

**Issue by embeepea** [nemac/data_snapshots#81]
create a url alias that brings up the Average Monthly Temperature snapshot at its most recently available date

**Comment by frimmel** [comment]
I have added an alias at http://dss-dev.nemac.org/data-snapshot/start. If this is working as expected then I will move these changes into code.

Also, the breadcrumb `catalog` was automatically added by the dev theme, it won't be there(or at least not with that text) in the live version.

**Comment by embeepea** [comment]
When I look at this page, here is what I see now:

![snapshot](https://cloud.githubusercontent.com/assets/2012435/6357954/478e3c38-bc36-11e4-87a8-1f27ba33b2f8.png)

Clearly we don't want the user login block there, and I'm guessing it's just there as a side-effect of some settings that are specific to our dev site.  But if it's easy to remove it from this page, I think that would be nice.  Can you do that?

Also, I'm not sure what you mean by "breadcrumb `catalog`".  Are you referring to the breadcrumb trail that consists simply of the `Home` link?  In any case, that `Home` link shouldn't be there.  Are you saying that it will not be there on the live site?

**Comment by frimmel** [comment]
The user login block is added by the dev theme, so it shouldn't be there in the live version. But for now I will hide it in the dev css module.

In investigating the breadcrumb stuff I installed the module path_breadcrumbs which seems like it has overridden the configuration in the dev module, which used the word `Catalog` in place of the word `Home`. I believe this is another thing Charlie will be able to easily configure on the live site but it is hard to know until it is shifted over.
