### ISSUE TITLE
An opportunity to inform our end users...

### ISSUE THREAD

**Issue by LuAnn** [nemac/data_snapshots#85]
This suggested enhancement <i>may</i> need to go on a "later" list, but I hope you'll give it serious consideration:

The recent climate.gov evaluation found that lots of folks don't recognize that all of our images are in the public domain and they can be reused without express permission. One way I can think of to let folks know they can use our images is to add the following notice to the bottom of the Download dialog box, just to the left of the buttons:
<i><b>These public-domain images are freely available for re-use. </b></i>

**Comment by frimmel** [comment]
This has been added. If you approve of the design I will push this up.

**Comment by LuAnn** [comment]
Could you drop the font size just a notch? It might even look OK in
italics, so it matches the "Select a Format:" text at the top.

I'm VERY pleased you could do this. I anticipate it will save us a lot of
email queries. :)

On Tue, Feb 24, 2015 at 12:36 PM, John Frimmel <notifications@github.com>
wrote:

> This has been added. If you approve of the design I will push this up.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nemac/data_snapshots/issues/85#issuecomment-75829020>.
>



-- 
LuAnn Dahlman
Communication Specialist
NOAA Climate Program Office
2020 LLC
*an Acentia Company*
Phone:  480-734-3124

**Comment by frimmel** [comment]
I have adjusted the styles slightly, should it be tweaked further?

**Comment by LuAnn** [comment]
Let's go with it! Dave Stroud may have come up with something else, but
this looks fine to me.

I'm super pleased that the message is exactly where people need to see it.

:) :) :)

On Tue, Feb 24, 2015 at 12:58 PM, John Frimmel <notifications@github.com>
wrote:

> I have adjusted the styles slightly, should it be tweaked further?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nemac/data_snapshots/issues/85#issuecomment-75833251>.
>



-- 
LuAnn Dahlman
Communication Specialist
NOAA Climate Program Office
2020 LLC
*an Acentia Company*
Phone:  480-734-3124
